# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Donald McKendrick
tagline:          'Developer and Entrepreneur'
description:      'Developer at Float and aspiring entrepreneur. I write about learning Rails and Startups'
side-description: 'Developer at <a href="http://floatapp.com">Float</a> and aspiring entrepreneur.'
url:              http://donaldmckendrick.com

author:
  name:           'Donald McKendrick'
  url:            https://twitter.com/deardonald

paginate:         5

# Custom vars
# version:          2.0.0

# github:
#   repo:           https://github.com/poole/hyde