# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Donald McKendrick

tagline:          'CTO and Entrepreneur'
description:      'CTO at <a href="http://www.storeluv.com" target="_blank">StoreLuv</a> and aspiring entrepreneur.'
side-description: 'CTO at <a href="http://www.storeluv.com" target="_blank">StoreLuv</a> and aspiring entrepreneur.'
url:              http://donaldmckendrick.com

author:
  name:           'Donald McKendrick'
  url:            https://twitter.com/deardonald

paginate:         5

# Custom vars
# version:          2.0.0

# github:
#   repo:           https://github.com/poole/hyde
